[profile.default]
optimizer = true
optimizer_runs = 20_000
src = 'src'
out = 'out'
libs = ['lib']
viaIR = true

[rpc_endpoints]
polygon="https://polygon.llamarpc.com"

mumbai = "https://polygon-mumbai.g.alchemy.com/v2/i7oRPAyOsL-UuAKRW5WfKlXeGqnF4u1E"
alfajores="https://alfajores-forno.celo-testnet.org"


[etherscan]

mumbai = { key = "1M7GD1BC9MKGI5EG1V8EP5I434XEKN651T",url="https://api-testnet.polygonscan.com/api" }

alfajores={ key = "9KAJAV8YCQ7EC7MGF6FSB8HB2U74AYT3CI", url="https://api-alfajores.celoscan.io/api" }

polygon = { key = "1M7GD1BC9MKGI5EG1V8EP5I434XEKN651T",url="https://api.polygonscan.com/api" }



