[profile.default]
optimizer = true
optimizer_runs = 20_000
src = 'src'
out = 'out'
libs = ['lib']
viaIR = true

[rpc_endpoints]
mumbai = "https://polygon-mumbai.g.alchemy.com/v2/i7oRPAyOsL-UuAKRW5WfKlXeGqnF4u1E"
alfajores="https://alfajores-forno.celo-testnet.org"

# Reference to remappings.txt
remappings = "remappings.txt"
